# Generated by Django 3.2 on 2021-05-03 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Meals',
            },
        ),
        migrations.CreateModel(
            name='ServicePercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'ServicePercentages',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiterid', models.IntegerField(default=0)),
                ('isitopen', models.BooleanField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tableid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table', to='app.table')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='MealsToOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('mealsid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.meal')),
                ('orderid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderid', to='app.order')),
            ],
            options={
                'verbose_name_plural': 'MealsToOrders',
            },
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('departmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='app.department')),
            ],
            options={
                'verbose_name_plural': 'MealCategories',
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='categoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.mealcategory'),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='order', serialize=False, to='app.order')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('servicefee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicefee', to='app.servicepercentage')),
            ],
            options={
                'verbose_name_plural': 'Checks',
            },
        ),
    ]
