# Generated by Django 3.2 on 2021-05-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mealstoorder_checkid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
